import { Component, OnInit, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog } from '@angular/material/dialog';
import { MatIconModule } from '@angular/material/icon';
import { MatSnackBar } from '@angular/material/snack-bar';
import { ApiService } from '../../core/api.service';
import { Column, DataTableComponent } from '../../shared/data-table.component';
import { openForm } from '../../shared/form-dialog.component';
import { JsonViewerDialog } from './json-viewer-dialog.component';

/** Versioned, dual-control-approved board reporting packs generated from the live dataset (FR-REP-007). */
@Component({
  selector: 'teta-board-packs',
  standalone: true,
  imports: [MatButtonModule, MatIconModule, DataTableComponent],
  template: `
    <div class="page">
      <div class="page-header">
        <h1>Board packs</h1>
        <button mat-flat-button color="primary" (click)="generate()"><mat-icon>add</mat-icon> Generate pack</button>
      </div>
      <teta-data-table [columns]="columns" [rows]="rows()" [actions]="actions" (rowClick)="view($event)" emptyText="No board packs generated yet." exportName="board-packs" />
      <ng-template #actions let-row>
        @if (row.status === 'Draft') { <button mat-icon-button (click)="approve(row, $event)" title="Approve"><mat-icon>check_circle</mat-icon></button> }
      </ng-template>
    </div>
  `
})
export class BoardPacksComponent implements OnInit {
  private readonly api = inject(ApiService);
  private readonly dialog = inject(MatDialog);
  private readonly snack = inject(MatSnackBar);
  readonly rows = signal<any[]>([]);

  columns: Column[] = [
    { key: 'number', label: 'Number' }, { key: 'period', label: 'Period' }, { key: 'packVersion', label: 'Version', type: 'number' },
    { key: 'title', label: 'Title' }, { key: 'status', label: 'Status', type: 'status' }, { key: 'generatedAtUtc', label: 'Generated', type: 'datetime' },
    { key: 'generatedBy', label: 'Generated by' }, { key: 'approvedAtUtc', label: 'Approved', type: 'datetime' }, { key: 'approvedBy', label: 'Approved by' }
  ];

  ngOnInit(): void { this.load(); }

  load(): void {
    this.api.get<any[]>('reports/board-packs').subscribe(r => this.rows.set(r));
  }

  async generate(): Promise<void> {
    const v = await openForm(this.dialog, { title: 'Generate board pack', fields: [
      { key: 'period', label: 'Period', required: true, hint: 'e.g. 2026 Q2' }, { key: 'title', label: 'Title', required: true, wide: true },
      { key: 'financialYear', label: 'Financial year (optional)', hint: 'e.g. 2026/27' }
    ] }, '760px');
    if (v) this.api.post('reports/board-packs', v).subscribe(() => this.load());
  }

  approve(row: any, e: Event): void {
    e.stopPropagation();
    this.api.post(`reports/board-packs/${row.id}/approve`).subscribe(() => {
      this.snack.open('Board pack approved.', 'OK', { duration: 3000 });
      this.load();
    });
  }

  view(row: any): void {
    this.api.get(`reports/board-packs/${row.id}`).subscribe((d: any) => {
      this.dialog.open(JsonViewerDialog, { data: { title: `${row.number} – ${row.title}`, json: d.dataset }, width: '900px', maxWidth: '96vw' });
    });
  }
}
